const EVENTS = {
  connection: "connection",
  CLIENT: {
    CREATE_ROOM: "CREATE_ROOM",
    JOINING_ROOM: "JOINING_ROOM",
    SEND_ROOM_MESSAGE: "SEND_ROOM_MESSAGE",
    CLIENT_INIT: "CLIENT_INIT",
  },
  SERVER: {
    ROOMS: "ROOMS",
    JOINED_ROOM: "JOINED_ROOM",
    ROOM_MESSAGE: "ROOM_MESSAGE",
    SERVER_INIT: "SERVER_INIT",
  },
};

export default EVENTS;
